### PR TITLE
Add unit tests for adapters

### PR DESCRIPTION
**Pull request by relekang**
#### Usage (copied from the changes to writing-adapters.md)

```js
const test = require('micro-analytics-cli/adapter-tests/unit-tests')

test({
 name: 'adapter-name',
 modulePath: path.resolve(__dirname, './index.js'),
})
```

The option object takes the following properties.

* `name` - The name of the adapter
* `modulePath` - The absolute path to the file you refer to in main in package.json
* `beforeEach` - Will be called in jest beforeEach hook, return a promise if it needs to do something async. We recommend cleaning the database here.
* `afterEach` - Will be called in jest afterEach hook, return a promise if it needs to do something async.
* `beforeAll` - Will be called in jest beforeAll hook, return a promise if it needs to do something async.
* `afterAll` - Will be called in jest afterAll hook, return a promise if it needs to do something async.

### CODE REVIEW

**Comment by mxstbr** [comment]
Have you tried running this with the redis adapter? Does it work??

**Comment by relekang** [comment]
Yes, this is with the repo linked locally.
```
~/dev/ma/adapter-redis(test) » jest
 PASS  ./test.js
  micro-analytics adapter redis
    ✓ should save and read (17ms)
    ✓ should return all saves on getAll (3ms)
    ✓ should have check whether a key is stored with has (1ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        0.702s, estimated 1s
Ran all test suites.
```

**Comment by mxstbr** [comment]
Awesome, is there anything left to be done?!

**Comment by relekang** [comment]
No, this pr is done 🙂 I will update the branch in redis repo when it is out.

**Comment by mxstbr** [comment]
Published as `1.2.0-10` (tagged as `dev`) from #31!

**Pull request merged**
